[project]
name = "container-demo"
version = "2024.10"
description = "This is a demo about using uv inside a docker container"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "cowsay>=6.1",
]
